### ISSUE TITLE
The template fails after update

### ISSUE THREAD

**Issue by underdub** [amirmasoud/beautiful#1]
After updating the template I get the following error:
wp-content/themes/beautiful/inc/customize/customize.php on line 22'

**Comment by amirmasoud** [comment]
It's because of PHP version as PHP docs says on the empty function:

Note: Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: `empty(trim($name))`. Instead, use `trim($name) == false`.

Alternatively if you can update your customize.php line 22-33 to the following:

``` PHP
<?php $beautiful_genral_font = get_theme_mod("beautiful_genral_font") ?>
<?php if(! empty($beautiful_genral_font) ) : ?>
@import url(http://fonts.googleapis.com/css?family=<?php echo $beautiful_genral_font ?>);
<?php endif ?>

<?php if( ! empty($beautiful_genral_font) ) : ?>
@import url(http://fonts.googleapis.com/css?family=<?php echo $beautiful_genral_font ?>);
<?php endif ?>
```

and just updated it to v1.1.1 https://themes.trac.wordpress.org/ticket/26219

Thanks for reporting.
